angular.module('app')
.factory('APPServices', ['BaseService', function(BaseService) {
	
	var serviceConfig = [{
		name: "login",
		method: "POST",
		url: "login/doLogin",
		config: {
			headers: {
				"Content-Type": 'application/x-www-form-urlencoded'
			}
		},
		showRequestMsg: false
	}, {
		name: 'logout',
		method: 'POST',
		url: 'secured/login/logout',
		successMsg: "Successfully logged out."
	}, {
		name: 'clearCache',
		method: 'POST',
		url: 'secured/admin/clearCache',
		successMsg: "Successfully cleared cache."
	}, {
		name: 'registerCompany',
		method: 'POST',
		url: 'company/registerCompany',
		showRequestMsg: false
	}, {
		name: 'getAllCompanies',
		method: 'POST',
		url: 'secured/company/getAllCompanies',
		showRequestMsg: false
	}, {
		name: 'getCompanyById',
		method: 'GET',
		url: 'secured/company/getCompanyById',
		showRequestMsg: false
	}, {
		name: 'getCompanyActivationByCompanyId',
		method: 'GET',
		url: 'secured/company/getCompanyActivationByCompanyId',
		showRequestMsg: false
	}, {
		name: 'createActivationDetail',
		method: 'POST',
		url: 'secured/company/createActivationDetail'
	}, {
		name: 'updateActivationDetail',
		method: 'POST',
		url: 'secured/company/updateActivationDetail'
	}, {
		name: 'createUser',
		method: 'POST',
		url: 'secured/user/createUser'
	}, {
		name: 'updateUser',
		method: 'PUT',
		url: 'secured/user/updateUser'
	}, {
		name: 'getAllNotifications',
		method: 'GET',
		url: 'secured/admin/getAllNotifications',
		showRequestMsg: false
	}, {
		name: 'getAllJobNotifications',
		method: 'GET',
		url: 'job/getJobNotifications',
		showRequestMsg: false
	}, {
		name: 'getAllRoleItems',
		method: 'GET',
		url: 'secured/role/getAllRoleItems',
		showRequestMsg: false
	}, {
		name: 'getAllRoles',
		method: 'POST',
		url: 'secured/role/getAllRoles',
		showRequestMsg: false
	}, {
		name: 'getRoleById',
		method: 'GET',
		url: 'secured/role/getRole',
		showRequestMsg: false
	}, {
		name: 'createRole',
		method: 'POST',
		url: 'secured/role/createRole'
	}, {
		name: 'updateRole',
		method: 'PUT',
		url: 'secured/role/updateRole'
	}, {
		name: 'getCompanyRoleAssociations',
		method: 'GET',
		url: 'secured/role/getCompanyRoleAssociations',
		showRequestMsg: false
	}, {
		name: 'createCompanyRoleAssociations',
		method: 'POST',
		url: 'secured/role/createCompanyRoleAssociations'
	}, {
		name: 'updateCompanyRoleAssociations',
		method: 'PUT',
		url: 'secured/role/updateCompanyRoleAssociations'
	}, {
		name: 'getAllUsers',
		method: 'POST',
		url: 'secured/user/getAllUsers',
		showRequestMsg: false
	}, {
		name: 'getUser',
		method: 'GET',
		url: 'secured/user/getUser',
		showRequestMsg: false
	}, {
		name: 'createUser',
		method: 'POST',
		url: 'user/createUser',
		showRequestMsg: false
	}, {
		name: 'updateUser',
		method: 'PUT',
		url: 'secured/user/updateUser',
		showRequestMsg: false
	}, {
		name: 'retrieveUserDeviceLocation',
		method: 'GET',
		url: 'secured/deviceLocation/getDeviceLocationsByUserId',
		showRequestMsg: false
	}, {
		name: 'getAllUserCallLogs',
		method: 'GET',
		url: 'secured/deviceLocation/getAllUserCallLogs',
		showRequestMsg: false
	}, {
		name: 'retrieveLastDeviceLocationByUserId',
		method: 'GET',
		url: 'secured/deviceLocation/retrieveLastDeviceLocationByUserId',
		showRequestMsg: false
	}, {
		name: 'retrieveAllLeads',
		method: 'POST',
		url: 'secured/lead/getAllLeads',
		showRequestMsg: false
	}, {
		name: 'createLead',
		method: 'POST',
		url: 'secured/lead/createLead',
		showRequestMsg: false
	}, {
		name: 'updateLead',
		method: 'PUT',
		url: 'secured/lead/updateLead'
	}, {
		name: 'retrieveLead',
		method: 'GET',
		url: 'secured/lead/getLead',
		showRequestMsg: false
	}, {
		name: 'submitLead',
		method: 'GET',
		url: 'secured/lead/submitLead'
	}, {
		name: 'retrieveLeadTasks',
		method: 'GET',
		url: 'secured/task/getAllLeadTasks',
		showRequestMsg: false
	}, {
		name: 'createLeadTask',
		method: 'POST',
		url: 'secured/task/createTask'
	}, {
		name: 'retrieveTask',
		method: 'GET',
		url: 'secured/task/getTask'
	}, {
		name: 'retrieveLeadTasksByLeadId',
		method: 'GET',
		url: 'secured/task/getAllTasksByLead',
		showRequestMsg: false
	}, {
		name: 'retrieveTasksByOpportunityId',
		method: 'GET',
		url: 'secured/task/getAllTasksByOpportunity',
		showRequestMsg: false
	}, {
		name: 'retrieveAllOpportunities',
		method: 'POST',
		url: 'secured/opportunity/getAllOpportunities',
		showRequestMsg: false
	}, {
		name: 'retrieveOpportunity',
		method: 'GET',
		url: 'secured/opportunity/getOpportunity',
		showRequestMsg: false
	}, {
		name: 'submitOpportunity',
		method: 'POST',
		url: 'secured/opportunity/submitOpportunity'
	}, {
		name: 'holdOpportunity',
		method: 'POST',
		url: 'secured/opportunity/holdOpportunity'
	}, {
		name: 'wonOpportunity',
		method: 'POST',
		url: 'secured/opportunity/wonOpportunity'
	}, {
		name: 'lostOpportunity',
		method: 'POST',
		url: 'secured/opportunity/lostOpportunity'
	}, {
		name: 'backToNegotiation',
		method: 'POST',
		url: 'secured/opportunity/backToNegotiation'
	}, {
		name: 'importFile',
		method: 'POST',
		url: 'attachment/lead/importFile',
		config: {
			headers: {
				"Content-Type": undefined
			}
		}
	}, {
		name: 'mapImportedFile',
		method: 'POST',
		url: 'secured/lead/mapImportedFile'
	}, {
		name: 'getAllLeadCompanies',
		method: 'POST',
		url: 'secured/leadCompany/getAllLeadCompanies',
		showRequestMsg: false
	}, {
		name: 'getAllLeadOpportunityTasks',
		method: 'GET',
		url: 'secured/task/getAllLeadOpportunityTasks',
		showRequestMsg: false
	}, {
		name: 'updateTask',
		method: 'PUT',
		url: 'secured/task/updateTask'
	}, {
		name: 'getMyOpenTasks',
		method: 'GET',
		url: 'secured/task/getMyOpenTasks',
		showRequestMsg: false
	}, {
		name: 'getMyOverdueTasks',
		method: 'GET',
		url: 'secured/task/getMyOverdueTasks',
		showRequestMsg: false
	}, {
		name: 'getMyLeads',
		method: 'GET',
		url: 'secured/lead/getMyLeads',
		showRequestMsg: false
	}, {
		name: 'getLeadStatistics',
		method: 'GET',
		url: 'secured/lead/getLeadStatistics',
		showRequestMsg: false
	}, {
		name: 'retrieveAllContacts',
		method: 'GET',
		url: 'secured/contact/getAllContacts',
		showRequestMsg: false
	}, {
		name: 'retrieveContact',
		method: 'GET',
		url: 'secured/contact/getContact',
		showRequestMsg: false
	}, {
		name: 'updateContact',
		method: 'PUT',
		url: 'secured/contact/updateContact'
	}, {
		name: 'getAllCampaigns',
		method: 'POST',
		url: 'secured/campaign/getAllCampaigns',
		showRequestMsg: false
	}, {
		name: 'getCampaign',
		method: 'GET',
		url: 'secured/campaign/getCampaign',
		showRequestMsg: false
	}, {
		name: 'createCampaign',
		method: 'PUT',
		url: 'secured/campaign/createCampaign'
	}, {
		name: 'updateCampaign',
		method: 'PUT',
		url: 'secured/campaign/updateCampaign'
	}, {
		name: 'getCampaignLeads',
		method: 'GET',
		url: 'secured/lead/getCampaignLeads',
		showRequestMsg: false
	}, {
		name: 'closeCampaign',
		method: 'POST',
		url: 'secured/campaign/closeCampaign'
	}, {
		name: 'getMyCalendarTasks',
		method: 'POST',
		url: 'secured/task/getMyCalendarTasks',
		showRequestMsg: false
	}];
	
	var services = BaseService.buildServices(serviceConfig);
	return services;
}]);